### ISSUE TITLE
r4300.zip is corrupt

### ISSUE THREAD

**Issue by vgturtle127** [Emu-Docs/Emu-Docs#10]
The r4300.zip file is corrupt, or at least I can't open it with anything I have (7-Zip, PeaZip, WinRAR, etc.).

This also applies to the @franckverrot copy on his repository. Not sure what is in this (presumably more datasheets or something) but I'm curious, so I want to know at least where you guys got this.

Hope this helps.

**Comment by vgturtle127** [comment]
@Emu-Docs Pinging to say that the copy of the r4300.zip has been fixed in the other repository.

**Comment by EmulatorDev** [comment]
And... fixed!

**Comment by vgturtle127** [comment]
@EmulatorDev Thank you!
