### ISSUE TITLE
sorting files: idea

### ISSUE THREAD

**Issue by superzazu** [Emu-Docs/Emu-Docs#5]
Hey,

For clarity I thought maybe we could put game-specific documents (ie Zelda1.txt) in a dedicated folder ? (like we did with the directory "test_roms")
Same question about the processors: what about the documents concerning CPU (and not directly consoles ?)

On a second note, that would be great to have a little README.md inside each folder, which points to the most important documents in the folder ?

**Comment by EmulatorDev** [comment]
Hmm, that's a great idea about putting the game-specific documents in a separate folder and having READMEs inside each folder.

Regarding documentation about CPUs, I've created a folder in the root directory called "Shared Components" and inside, there's a directory called "CPU 65xx" for documentation regarding that CPU. Then, inside the "Nintendo Entertainment System" directory, I've created symlink to the "CPU 65xx" directory.

Also, I've added you and shonumi as contributors to this repository. Please let me know if I messed up and you still don't have commit access.

**Comment by superzazu** [comment]
Okay thanks :-)

Should we include documents which discusses rom hacking ? For example lahack.txt "THE FIRST UNOFFICAL LINK'S AWAKINING DX ROM HACKING DOCUMENT"

**Comment by EmulatorDev** [comment]
Hmm, honestly, I'm not sure. I think I've already included a doc called "THE ART OF ROM HACKING" somewhere. I suppose ROM hacking docs are fine (I suppose they could go under "game_documentation") but they're definitely low-priority.

**Comment by superzazu** [comment]
"ERROR: Permission to Emu-Docs/Emu-Docs.git denied to superzazu.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists."

**Comment by superzazu** [comment]
?
